services:
  backend_absensi_smk:
    image: absensi-backend:1.0
    container_name: backend_absensi_smk
    working_dir: /app
    restart: unless-stopped
    command: ["php", "artisan", "octane:start", "--server=frankenphp", "--host=0.0.0.0", "--port=8000"]
    depends_on:
      - postgres
      - redis
    ports:
      - "8000:8000"
    environment:
      APP_ENV: production
      APP_DEBUG: false
      APP_URL: https://siakad.rplsmknusa.net

      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: absensi_smk
      DB_USERNAME: absensi_smk
      DB_PASSWORD: Smknpur@747

      REDIS_HOST: redis
      REDIS_PORT: 6379

      CACHE_STORE: redis
      SESSION_DRIVER: redis
      QUEUE_CONNECTION: redis

      OCTANE_SERVER: frankenphp
    volumes:
      - ./backend-absensi:/app
      - ./backend-absensi/storage:/app/storage
    networks:
      - network_absensi_smk

  queue:
    image: absensi-backend:1.0
    container_name: absensi_queue
    restart: unless-stopped
    working_dir: /app
    command: ["php","artisan","queue:work","--sleep=3","--tries=3","--max-time=3600"]
    volumes:
      - ./backend-absensi:/app
      - ./backend-absensi/storage:/app/storage
    depends_on:
      - postgres
      - redis
    environment:
      APP_ENV: production
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: absensi_smk
      DB_USERNAME: absensi_smk
      DB_PASSWORD: Smknpur@747
      REDIS_HOST: redis
      REDIS_PORT: 6379
      CACHE_STORE: redis
      SESSION_DRIVER: redis
      QUEUE_CONNECTION: redis
    networks:
      - network_absensi_smk

  postgres:
    image: postgres:15-alpine
    container_name: absensi_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: absensi_smk
      POSTGRES_USER: absensi_smk
      POSTGRES_PASSWORD: Smknpur@747
    volumes:
      - ./backend-absensi/pgdata:/var/lib/postgresql/data
    networks:
      - network_absensi_smk

  redis:
    image: redis:7-alpine
    container_name: absensi_redis
    restart: unless-stopped
    networks:
      - network_absensi_smk

networks:
  network_absensi_smk:

volumes:
  pgdata:
  storage:
