services:
  backend_absensi_smk:
    build: .
    container_name: backend_absensi_smk
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    ports:
      - "8000:8000"
    environment:
      APP_ENV: production
      APP_DEBUG: false
      APP_URL: https://yourdomain.com

      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: absensi_smk
      DB_USERNAME: absensi_smk
      DB_PASSWORD: Smknpur@747

      REDIS_HOST: redis
      REDIS_PORT: 6379

      CACHE_STORE: redis
      SESSION_DRIVER: redis
      QUEUE_CONNECTION: redis

      OCTANE_SERVER: frankenphp
    volumes:
      - storage:/app/storage
    networks:
      - network_absensi_smk

  # queue:
  #   build: .
  #   container_name: laravel_queue
  #   command: php artisan queue:work --sleep=3 --tries=3 --max-time=3600
  #   restart: unless-stopped
  #   depends_on:
  #     - redis
  #     - postgres
  #   environment:
  #     APP_ENV: production
  #     DB_HOST: postgres
  #     REDIS_HOST: redis
  #   volumes:
  #     - storage:/app/storage
  #   networks:
  #     - network_absensi_smk

  postgres:
    image: postgres:15-alpine
    container_name: laravel_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: absensi_smk
      POSTGRES_USER: absensi_smk
      POSTGRES_PASSWORD: Smknpur@747
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - network_absensi_smk

  redis:
    image: redis:7-alpine
    container_name: laravel_redis
    restart: unless-stopped
    networks:
      - network_absensi_smk

networks:
  network_absensi_smk:

volumes:
  pgdata:
  storage:
