services:
  # API Server (FrankenPHP + Octane)
  api:
    build: .
    container_name: laravel_api
    restart: always
    environment:
      APP_SERVICE: api
      VARIABLES_HTTP_PORT: 80
    volumes:
      - ./:/app
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    depends_on:
      - db
      - redis

  # Laravel Queue Worker
  worker:
    build: .
    container_name: laravel_worker
    restart: always
    command: php artisan queue:work --tries=3 --timeout=90
    volumes:
      - ./:/app
    depends_on:
      - db
      - redis

  # Database PostgreSQL
  db:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE:-laravel}
      POSTGRES_USER: ${DB_USERNAME:-sail}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
    volumes:
      - pgdata:/var/lib/postgresql/data

  # Redis for Cache & Queue
  redis:
    image: redis:alpine
    container_name: redis_cache
    restart: always

volumes:
  pgdata:
